// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaejmwcrhdqavrkzyira.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZWptd2NyaGRxYXZya3p5aXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDM5MTcsImV4cCI6MjA2MjQ3OTkxN30.joH6G1GwGuYWrYM29z8TeaN6GAkwIeIS4iwW6YJCifw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);